exchange:
  name: bybit
  network: mainnet
  category: linear

risk:
  max_leverage: 7
  max_symbols: 3
  total_budget_usdt: null
  use_balance_ratio: 0.9

orderbook:
  min_depth_usd: 20000

entry_exit:
  tp1: 0.0010
  sl: 0.0015
  trail_after_tp1: 0.0008

funding_time:
  avoid_taker_within_min: 5
