exchange:
  name: bybit
  network: testnet
  category: linear

risk:
  max_leverage: 7
  max_symbols: 5
  total_budget_usdt: null
  use_balance_ratio: 1.0

orderbook:
  min_depth_usd: 50000

entry_exit:
  tp1: 0.0012
  sl: 0.0018
  trail_after_tp1: 0.0008

funding_time:
  avoid_taker_within_min: 5
