name: CI

on:
  push:
    branches: [ "feat/spec-v1" ]
  pull_request:
    branches: [ "feat/spec-v1" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11" ]

    env:
      STUB_MODE: "true"
      PAPER_MODE: "true"
      LIVE_MODE: "false"
      TESTNET: "false"
      MPLBACKEND: "Agg"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ruff
        run: ruff check .

      - name: Pytest
        run: pytest -q

      - name: Build paper report
        run: |
          mkdir -p reports
          python bot/scripts/run_paper.py

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper-report-${{ matrix.python-version }}
          path: reports/paper.html
