name: CI

on:
  push:
    branches: [ develop, feat/** ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: ruff check .
      - name: Test
        env:
          STUB_MODE: 'true'
        run: pytest -q
      - name: Run paper
        env:
          STUB_MODE: 'true'
          PAPER_MODE: 'true'
        run: python bot/scripts/run_paper.py
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/**
